name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'campfire-frontend/**'
      - 'campfire-backend/**'
      - 'adapter_frontend/**'
      - 'messaging-system/**'

env:
  DOCKER_DRIVER: overlay2

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12-dind
        options: --privileged
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Docker Login
      run: docker login -u "${{ secrets.CI_REGISTRY_USER }}" -p "${{ secrets.CI_REGISTRY_PASSWORD }}"

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - name: Log modified files
      run: echo "Modified files - ${{ toJson(github.event.head_commit.modified) }}"

    - name: Log modified files from event
      run: echo "Modified files - ${{ toJson(github.event.pull_request.changed_files) }}"

    - name: Get changed files with predefined action
      id: changed-files
      uses: tj-actions/changed-files@v37

    - name: List all changed files
      run: |
        echo '# FILES with tj-actions/changed-files' >> "${GITHUB_STEP_SUMMARY}"
        echo '' >> "${GITHUB_STEP_SUMMARY}"
        echo '```' >> "${GITHUB_STEP_SUMMARY}"

        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed" >> "${GITHUB_STEP_SUMMARY}"
        done

        echo '```' >> "${GITHUB_STEP_SUMMARY}"
      
    - name: Build and Push campfire-frontend
      if: contains(steps.changed-files.outputs.all_changed_files, 'campfire-frontend/')
      run: |
        cd campfire-frontend
        docker build -t campfirert/campfire-frontend:${{ github.sha }} .
        docker tag campfirert/campfire-frontend:${{ github.sha }} campfirert/campfire-frontend:latest
        docker push campfirert/campfire-frontend:${{ github.sha }}
        docker push campfirert/campfire-frontend:latest

    - name: Build and Push campfire-backend
      if: contains(steps.changed-files.outputs.all_changed_files, 'campfire-backend/')
      run: |
        cd campfire-backend
        docker build -t campfirert/campfire-backend:${{ github.sha }} .
        docker tag campfirert/campfire-backend:${{ github.sha }} campfirert/campfire-backend:latest
        docker push campfirert/campfire-backend:${{ github.sha }}
        docker push campfirert/campfire-backend:latest

    - name: Build and Push adapter_frontend
      if: contains(steps.changed-files.outputs.all_changed_files, 'adapter-frontend/')
      run: |
        cd adapter_frontend
        docker build -t campfirert/adapter_frontend:${{ github.sha }} .
        docker tag campfirert/adapter_frontend:${{ github.sha }} campfirert/adapter_frontend:latest
        docker push campfirert/adapter_frontend:${{ github.sha }}
        docker push campfirert/adapter_frontend:latest

    - name: Build and Push messaging-system
      if: contains(steps.changed-files.outputs.all_changed_files, 'messaging-system/')
      run: |
        cd messaging-system
        docker build -t campfirert/messaging-system:${{ github.sha }} .
        docker tag campfirert/messaging-system:${{ github.sha }} campfirert/messaging-system:latest
        docker push campfirert/messaging-system:${{ github.sha }}
        docker push campfirert/messaging-system:latest
